---
title: "Practica 1 Estadistica Avanzada"
author: "Ramon Soto"
date: '2022-03-05'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1 Carga de datos
## Volcado en DAtaframe y presentacion de datos


```{r}


Salarios <- 
  read.table("D:/uoc/estadistica avanzada/sesion 1/CensusIncomedataset.csv", 
  header=TRUE, stringsAsFactors=TRUE, sep=";", na.strings="NA", dec=".", 
  strip.white=TRUE)
  head(Salarios)
  str(Salarios)
  summary(Salarios)

```

# 2 Verificacion y normalizacion de las variables
```{r}

#borramos variables
Salarios <- within(Salarios, {
   capital_gain <- NULL
   capital_loss <- NULL
   fnlwgt <- NULL 
  })

# quitamos filas con mas de cinco NA
nrow(Salarios)
Indices<-which(rowSums(is.na(Salarios))>=5)
Salarios[Indices,]
Indices
Salarios<-Salarios[-Indices,]
nrow(Salarios)

#categorizamos los años de educacion

attach(Salarios)
education_cat<-education_num
education_cat[education_num<7]<-"Primaria"
education_cat[education_num>=7 & education_num<9]<-"Secundaria"
education_cat[education_num>=9 & education_num<13]<-"Universitaria"
education_cat[education_num>=13]<-"Postuniversitaria"
Salarios$education_cat<-education_cat
table(education_cat)

#renombramos variable
names(Salarios)[c(9)] <- c("gender")


```


## 3 Duplicados

```{r}
##En primer lugar s e de ja de tratar los valores de CS_ID como factores para poder nuevos en caso de que sea necesario
Salarios$CS_ID<-as.character(Salarios$CS_ID)

##Se obtienen los  indices de los registros con valores de CS_ID  ya usados en registros anteriores
Indices<-which(duplicated(Salarios$CS_ID))


##estos son los valores repetidos
Salarios[Indices,c("CS_ID")]

##se parte del CS_ID del ukltimo registro y se le suma 1
##se hace una busqueda hacia adelante para encontrar el siguiente valor no asignado
##Se repite el proceso para cada registro que tenga un valor de CS_ID repetido

iterador<-1
for (i in Indices){
  
  codigo_aux<- paste("CS",as.character(nrow(Salarios)+iterador),sep = "")
  while(!identical(which(Salarios$CS_ID==codigo_aux),integer(0))){
    iterador<-iterador+1
    codigo_aux<- paste("CS",as.character(nrow(Salarios)+iterador),sep = "")
  }
  
  cat("Para el registro ",i,"  se asigna el codigo: ",codigo_aux,"\n")
  Salarios[i,c("CS_ID")]<-codigo_aux
  iterador<-iterador+1
  
}

##Verificamos que ya no hay  duplicados 
Indices<-which(duplicated(Salarios$CS_ID))
Salarios[Indices,c("CS_ID")]





```

## 4 Normalizacion de las variables cualitativas

```{r}
#recortar espacios en blanco en valores de las variables cualitativas
variables_cualitativas<-names(Filter(is.factor,Salarios))

for(name  in variables_cualitativas){
  Salarios[[name]]<-factor(trimws(Salarios[[name]],"l"))
}

#observamos el orden en el que se encuentran las categorías y ese es el que aplicamos para recortarlas a un caracter
levels(Salarios$marital_status)
levels(Salarios$marital_status)<-c("D","M","S","X","W")
levels(Salarios$marital_status)
head(Salarios$marital_status)
table(Salarios$marital_status)

#distribucion de marital_Status
barplot(table(Salarios$marital_status), main = "Frequencia absoluta",
        col = rainbow(5))
        
#refactorizacion de la variable gender
library(car)
#niveles actuales
levels(Salarios$gender) 
Salarios$gender <- Recode(Salarios$gender, 
                   '"Fem"="f"; "Female"="f";"F"="f"; "female"="f"; "M"="m"; "male"="m"; "Male"="m"',
                   as.factor=TRUE)
#niveles despues de refactorizar                   
levels(Salarios$gender) 
#distribucion de gender
barplot(table(Salarios$gender), main = "Frequencia absoluta",
        col = rainbow(2))


```

#5 normalizacion variables cuantitativas
```{r}
#Para age  y educartion_num se hace un casting a integer

Salarios$age<-as.integer(Salarios$age)
Salarios$education_num<-as.integer(Salarios$education_num)
head(Salarios[, c('age', 'education_num')])
tail(Salarios[, c('age', 'education_num')])



## Se hace una copia de de income y  numeric se hace una copia para comparar el antes y el despues de la nomalizacion

income_before<-Salarios$income
hours_per_week_before<-Salarios$hours_per_week


##Se sustituyen las comas por puntos

Salarios$hours_per_week<-gsub(",", ".", Salarios$hours_per_week)
Salarios$income<-gsub(",", ".", Salarios$income)

## Se obtienen los indices de los valores expresados en miles de euros en income
K_EUR_Indice<-regexpr("Milers",Salarios$income)

##Se obtienen los indices de los registros que contienen valores numericos válidos para income 
Indice_aux_hours_per_week<-regexpr("[[:digit:]]+\\.*[[:digit:]]*",Salarios$hours_per_week)
Indice_aux_income<-regexpr("[[:digit:]]+\\.*[[:digit:]]*",Salarios$income)

##Aux contiene los valores numericos aislados del resto de caracteres
Aux_hours_per_week<-regmatches(Salarios$hours_per_week,regexpr("[[:digit:]]+\\.*[[:digit:]]*",Salarios$hours_per_week))
Aux_income<-regmatches(Salarios$income,regexpr("[[:digit:]]+\\.*[[:digit:]]*",Salarios$income))

##En caso de que hubiera, aquí se mostrarian los indices y valores que no tenian un valor valido
which(Indice_aux_hours_per_week==-1)
Salarios[which(Indice_aux_hours_per_week==-1), c('hours_per_week')]
which(Indice_aux_income==-1)
Salarios[which(Indice_aux_income==-1), c('income')]

##Para el resto de registros, con valores de income validos , se hace la modificación
Salarios[which(Indice_aux_hours_per_week!=-1), c('hours_per_week')]<-Aux_hours_per_week
Salarios[which(Indice_aux_income!=-1), c('income')]<-Aux_income

## paso a numeric
Salarios$income<-as.numeric(Salarios$income)
Salarios$hours_per_week<-as.numeric(Salarios$hours_per_week)

##Ayudandonos del vector de indices que contiene los registros qen los que income esta expresado en miles de euros pasamos a unidades de euros
Salarios[which(K_EUR_Indice!=-1), c('income')]<-Salarios[which(K_EUR_Indice!=-1), c('income')]*1000



##se muestran  los nuevos ¡valores de las dos columnas comparados con los que traia la tabla originalmente

compara_income= cbind(Salarios$income,income_before)

head(compara_income)
tail(compara_income)
compara_hours_per_week= cbind(Salarios$hours_per_week,hours_per_week_before)

head(compara_hours_per_week)
tail(compara_hours_per_week)

# head(Salarios[, c('hours_per_week', 'income')])
# head(hours_per_week_before)
# head(income_before)
# tail(Salarios[, c('hours_per_week', 'income')])
# tail(hours_per_week_before)
# tail(income_before)


```


